### ISSUE TITLE
Teensy4.1 project with SD Library not linking

### ISSUE THREAD

**Issue by hemantkapoor** [knickish/teensy_docker#6]
Tried a simple program to test SDFAT library and there were loads of linker issue.

Figured out that SDFAT library has below sub directories
ExFatLib
FatLib
FsLib
SdCard
SpiDriver
common
iostream

And libs_cmake.py is not written in a generic way to take into account these sub folders

**Comment by knickish** [comment]
I will try and take a look at this this weekend

**Comment by hemantkapoor** [comment]
Did you get time to look into this?

**Comment by kiwiDaveENZED** [comment]
In case it's any help I had similar issues so removed SD, Audio and USBHost from my dockerfile (copied relevant step below). I then added 'SD' separately under the 'libs' folder. I also added the USBHost_t36 library in the same way. I haven't used the audio library yet but assume it would work in the same manner.

```
# Remove SD as incompatible with teensy. Audio has dependency on SD so remove also
WORKDIR /teensyduino
RUN mkdir -p /teensyduino/install && \
    mkdir -p /teensyduino/build
ADD internal/CMake/project_root/* /teensyduino/
ADD internal/CMake/toolchain/* /teensyduino/
ADD config.json /teensyduino/
ADD internal/CMake/select_all/CMakeLists.txt /teensyduino/cores/teensy3
ADD internal/CMake/select_all/CMakeLists.txt /teensyduino/cores/teensy4
ADD internal/CMake/select_all/CMakeLists.txt /teensyduino/src
RUN rm /teensyduino/cores/teensy3/main.* && \
    rm /teensyduino/cores/teensy4/main.* && \
    rm /teensyduino/cores/teensy4/Blink.cc  && \
    rm -r ./libraries/SD && \
    rm -r ./libraries/Audio && \
    rm -r ./libraries/USBHost_t36
```

**Comment by hemantkapoor** [comment]
The workaround I found was rather than creating static libs for libraries, I included them to compile as normal files and it all worked.

Now I am trying to port the teensy library to latest version i.e. 1.5.9 but having no joy with it.

**Comment by knickish** [comment]
Apologies for slow response, was busier than expected. Could you post an example of what you were trying to do? I put up a PR (#8 ) that should hopefully fix it, but would like to verify before merging"

**Comment by hemantkapoor** [comment]
My test code is very sime 

`
```
#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <BufferedPrint.h>
#include <FreeStack.h>
#include <MinimumSerial.h>
#include <RingBuf.h>
#include <SdFat.h>
#include <SdFatConfig.h>
#include <sdios.h>

SdFs* g_sdHandler = nullptr;
SDClass* SD = nullptr;

void setup()
{
	Serial7.begin(115200);
    g_sdHandler = new SdFat();
    SD = new SDClass(g_sdHandler);

	if (!SD->begin(BUILTIN_SDCARD)) 
	{
		Serial7.println("Card failed, or not present");
		// don't do anything more:
		return;
	}
  Serial7.println("card initialized.");	
}
void loop()
{
	Serial7.println("Hello from docker\n");
	delay(500);
}
extern "C" int main(void)
{
	// Arduino's main() function just calls setup() and loop()....
	setup();
	while (1) {
		loop();
		yield();
	}
}
```
`

**Comment by hemantkapoor** [comment]
Also is it possible to port to latest Teensy version i.e. 1.5.9. As in my project I am using things like "HardwareSerialIMXRT" which is not part of old lib.

I did manage to update the docker file for the version (se attached
[Dockerfile.zip](https://github.com/user-attachments/files/16052608/Dockerfile.zip)
)

But get linker error: 
arm-none-eabi-g++: fatal error: '-fuse-linker-plugin', but liblto_plugin.so not found

when building even a simple hello world project...

May be someone more smart than me could solve this mystery :)

**Comment by knickish** [comment]
@hemantkapoor I tested that code against the branch and it seemed to rely on the later version of Teensy unless I'm missing something. Will see if I can fix that issue with the dockerfile you've provided

**Comment by knickish** [comment]
Made a fair amount of progress on getting 1.5.9 working based on that Dockerfile, will open a PR for that when I have it finished up

**Comment by hemantkapoor** [comment]
Nice...
I am stuck with the linker error

arm-none-eabi-g++: fatal error: '-fuse-linker-plugin', but liblto_plugin.so
not found

**Comment by hemantkapoor** [comment]
Did you manange to get it working?

**Comment by knickish** [comment]
I have not. I usually don't have a lot of time during the work week; will try to get it resolved soon

**Comment by knickish** [comment]
I got past the `liblto_plugin.so` error. Working on resolving another linking issue with the SDFat library now

**Comment by hemantkapoor** [comment]
Great stuff.... Can you please let me know how you fixed "liblto_plugin.so" issue.

I created a very simple project with no libraries and updated cmake to have following flag set in linker command - 

`-fno-use-linker-plugin`

 . This stopped giving me the issue.... But I got below errors then 


`
[100%] Linking CXX executable MAIN
/usr/bin/cmake -E cmake_link_script CMakeFiles/MAIN.dir/link.txt --verbose=1
.....
....
....
ld: skipping incompatible /teensyduino/include/libarm_cortexM7lfsp_math.a when searching for -larm_cortexM7lfsp_math
ld: cannot find -larm_cortexM7lfsp_math

ld: skipping incompatible /teensyduino/include/libstdc++_nano.a when searching for -lstdc++_nano
ld: cannot find -lstdc++_nano
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: relocations in generic ELF (EM: 40)
ld: CMakeFiles/MAIN.dir/src/main.cpp.obj: error adding symbols: file in wrong format
make[2]: *** [CMakeFiles/MAIN.dir/build.make:3837: MAIN] Error 1
make[2]: Leaving directory '/teensyduino/build'
make[1]: *** [CMakeFiles/Makefile2:264: CMakeFiles/MAIN.dir/all] Error 2
make[1]: Leaving directory '/teensyduino/build'
make: *** [Makefile:87: all] Error 2
`

**Comment by knickish** [comment]
Going to reopen this since the title issue is still a problem. I included my changes that allow the container to build with 1.59 in #9, although there is still lots of debug stuff that I haven't cleaned up yet. 

I haven't had time to dig into the linking issue, it's failing to build an SD example with:
```
/teensyduino/bin/arm-none-eabi-ld: libraries/SdFat/libSdFat.a(SdSpiTeensy3.cpp.obj): in function `SdSpiArduinoDriver::begin(SdSpiConfig)':
/teensyduino/libraries/SdFat/src/SpiDriver/SdSpiTeensy3.cpp:46: undefined reference to `SPI'
/teensyduino/bin/arm-none-eabi-ld: libraries/SdFat/libSdFat.a(SdSpiTeensy3.cpp.obj): in function `SPIClass::transfer(void*, unsigned int)':
/teensyduino/libraries/SPI/SPI.h:1292: undefined reference to `SPIClass::transfer(void const*, void*, unsigned int)'
/teensyduino/bin/arm-none-eabi-ld: /teensyduino/libraries/SPI/SPI.h:1292: undefined reference to `SPIClass::transfer(void const*, void*, unsigned int)'
/teensyduino/bin/arm-none-eabi-ld: libraries/SdFat/libSdFat.a(SdSpiTeensy3.cpp.obj): in function `SdSpiArduinoDriver::begin(SdSpiConfig)':
/teensyduino/libraries/SdFat/src/SpiDriver/SdSpiTeensy3.cpp:46: undefined reference to `SPIClass::begin()'
/teensyduino/bin/arm-none-eabi-ld: /teensyduino/libraries/SdFat/src/SpiDriver/SdSpiTeensy3.cpp:46: undefined reference to `SPIClass::begin()'
/teensyduino/bin/arm-none-eabi-ld: libraries/SdFat/libSdFat.a(SdSpiTeensy3.cpp.obj): in function `SdSpiArduinoDriver::end()':
/teensyduino/libraries/SdFat/src/SpiDriver/SdSpiTeensy3.cpp:54: undefined reference to `SPIClass::end()'
```

will continue to work on it as I have time

**Comment by hemantkapoor** [comment]
Ok...

But did you manage age to have a successful build without SD library?
